### ISSUE TITLE
Script bloqué à la verip_app_ouverte

### ISSUE THREAD

**Issue by Yukuu974** [ThomasTra/Bravolobot#1]
Bonjour,
Le script est bloqué pour checker si l'app est ouverte. 
![image](https://user-images.githubusercontent.com/80755612/111297040-75afee80-864d-11eb-86c1-04c0d5131532.png)

**Comment by FrenchGithubUser** [comment]
Est-ce que l'application est lancée et le bouton "JOUER" est visible ?
Est-ce que l'émulateur est bien en 1920x1080 pixels ?
Si oui, essaie d'enlever le .rotate sur les images dans le script, certains ordis font tourner le screenshot et d'autres non, ça peut être la raison.
Je vais l'enlever dans le script du repo, tu peux re-cloner le repo et ré-essayer

**Comment by Yukuu974** [comment]
Le bouton "JOUER" est bien visible
L'émulateur est bien en 1920x1080 (j'ai bloqué en mode paysage pour qu'il reste dans cette résolution)
Avec et sans rotate je suis toujours bloqué 
![screen](https://user-images.githubusercontent.com/80755612/111317938-e1518600-8664-11eb-80ac-dedae3ca2d7d.jpg)
au même endroit

**Comment by Yukuu974** [comment]
En essayant de débug j'ai trouvé ou ça coince, le try ne passe pas sur cette "lignetxt_img = pytesseract.image_to_string(file, lang="fra")"

**Comment by FrenchGithubUser** [comment]
T'as réussi à le faire marcher finalement ?
Et est-ce que Pytesseract trouve bien le fichier traineddata ?
Et est-ce que le fichier check_app_ouverte.txt est bien créé ?

**Comment by Yukuu974** [comment]
Non je n'ai pas réussi.
Je ne sais pas si il trouve le fichier, je l'ai bien déplacé dans le répertoire tessdata
Non il n'y a pas de txt qui est créé

**Comment by FrenchGithubUser** [comment]
Essaie d'enregistrer `file = Image.open("screen.raw").crop((110, 1045, 596, 1149))` sous format jpg et regarde ce qu'il y a dessus.
Si ça a bien crop sur le bouton jouer alors print la ligne du dessous pour voir ce que pytesseract lis dans l'image.
Soit ça crop pas au bon endroit, soit pytesseract n'arrive pas à lire ce qu'il y a sur la photo.
PS : et c'est normal qu'aucun fichier txt ne soit créé, c'était dans une ancienne version que ça devait le faire

**Comment by Yukuu974** [comment]
En effet le problème vient du crop au mauvais endroit, plus qu'à trouver les bonnes coordonnées
![debug](https://user-images.githubusercontent.com/80755612/111367754-56d54a80-8695-11eb-97fd-bc57a6c0f645.png)

**Comment by FrenchGithubUser** [comment]
J'avais fait ça avec paint, ouvres le screenshot dans paint et en bas à gauche tu as les coordonnées du curseur (il me semble qu'il faut les coordonnées du rectangle en haut à gauche puis en bas à droite).
Dis moi si les autres coordonnées (pour les autres boutons) sont aussi faussées
C'est en tous cas étonnant parce que le bouton jouer n'a pas bougé depuis que j'ai écrit le script...

**Comment by Yukuu974** [comment]
J'ai crop en (300, 1600, 700, 1700) et j'obtiens ça
![debug](https://user-images.githubusercontent.com/80755612/111380870-3614f100-86a5-11eb-9dd5-712317ef0a87.png)
Pytesseract ne détecte pas de texte :/

**Comment by FrenchGithubUser** [comment]
Est-ce que le fichier traineddata est bien utilisé ?
Si tu print ce que tesseract lis il n'y a rien ?

**Comment by Yukuu974** [comment]
Comment savoir si j'utilise le fichier traineddata ?
Non tesseract ne lis rien

**Comment by FrenchGithubUser** [comment]
En tous cas ça crop au bon endroit, la bonne orientation, essaie de chercher sur internet d'où peut venir le fait que tesseract n'arrive rien à lire parce que le problème ne vient pas du script
